version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    ports:
      - 2717:27017
    volumes:
      - mongodb_data_container:/data/db

  client:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ../client:/etc/nginx/html:ro
      - ./conf.d/:/etc/nginx/conf.d:ro

volumes:
  mongodb_data_container: